---
output: pdf_document
---


Experiment e11 - Pragmatic Listener experiment with alternatives
```{r}

rm(list=ls())
setwd("~/Desktop/Projects/scalar_implicature/")
source("analysis/useful_dplyr.R")
library(tidyr)
library(dplyr)
library("rjson")
# commentary on weird RMarkdown bug
# https://github.com/hadley/xml2/issues/34
```

Data prep
---------
```{r}

# make sure to set directory path to 'production-results/e11/'
results_path = "production-results/e11/"
files <- dir(results_path, pattern = "*.json")
d.raw <- data.frame()

for (f in files) {
  jf <- paste(results_path,f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- data.frame(workerid = jd$WorkerId, 
                   scale = jd$answer$data$scale,
                   degree = jd$answer$data$degree,
                   stars = as.numeric(jd$answer$data$judgment),
                   language = jd$answer$data$language,
                   gender = jd$answers$data$gender,
                   age = jd$answers$data$age)
  d.raw <- bind_rows(d.raw, id)
}

# Number of participants
length(unique(d.raw$workerid))
```

Holding off on exclusions (but exclusion code here)
---------------------------------------------------
```{r}
d <- d.raw %>% filter(scale != "training1")
# compliant <- d.raw %>% 
#   filter(grepl("training", scale)) %>%
#   group_by(workerid) %>%
#   summarise(compliant = judgment[scale == "training1" & degree == "hi"] > 3 & 
#               judgment[scale == "training1" & degree == "low"] < 3)
#   
# d <- d.raw %>% 
#   left_join(compliant) %>%
#   filter(grepl(pattern = "english", 
#                language, ignore.case = TRUE), 
#          domain != "training1", 
#          domain != "training2", 
#          compliant == TRUE)
```

Main analysis below
-------------------

Let's remove training runs
```{r}
#d.raw = d.raw[c(-1, -2), ]       # remove first two rows
#d = d.raw %>% filter(scale != "training1")
```

Populate a new df
```{r}
density <- d %>%
  group_by(degree, scale) %>%
  mutate(n = n()) %>%
  group_by(degree, scale, stars) %>%
  summarise(prop = n() / n[1])
```

Plot our pragmatic listener judgments
```{r}
write.csv(density, "models/e11.csv", row.names=FALSE)
pdf("plots/e11.pdf", width = 8, height = 4)
qplot(stars, prop, facets = degree ~ scale, 
      geom="bar", stat = "identity",
      binwidth = 1, data=density)
dev.off()
```


```{r}
# prop.calc = function(scalar, degree, stars, df) {
#   total = sum(df[(df$scale == scalar) & (df$degree == degree), "cnt.judgment"])
#   prop = df[(df$scale == scalar) & (df$degree == degree) & (df$stars = stars), "cnt.judgment"]
#   return(prop / total)
# }
# scales = rep("some_all", 5)
# stars = seq(1:5)
# degree = rep("hi1", 5)
# cnt.judgment = c(0, 0, 0, 2, 28)
# 
# df = data.frame(scales, stars, degree, cnt.judgment)
# prop.calc("some_all", "hi1", 1, df)
# 
# ms$judgment.prop = ms$judgment
# # write to csv for model
# #write.csv(ms, "models/e10.csv", row.names=FALSE)


```
