---
title: "e9_altsAnalysis"
author: "BPeloquin"
date: "October 2, 2015"
output: html_document
---

```{r}
rm(list = ls())
#library(rjson)
library(jsonlite)
fp = "~/Desktop/Projects/scalar_implicature/analysis/"
setwd("~/Desktop/Projects/scalar_implicature/")
```

**Analysis of alternative gathering experiment**

Data cleaning in alts_analysis.py

Explore
--------
```{r}
d1 = fromJSON("analysis/edited_alts.json", simplifyDataFrame=T)
d1 = as.data.frame(d1, stringsAsFactors = FALSE)
```

```{r}
library(tidyr)
library(dplyr)
d <- d1 %>% 
  select(-high, -low) %>%
  gather(base, alt, 
         palatable, liked, good, loved, some, all, 
         delicious, excellent, memorable, unforgettable) %>%
  mutate(base = as.character(base)) %>%
  rowwise %>%
  mutate(scale = ifelse(base == "some" | base == "all", "some_all", 
                        ifelse(base == "palatable" | base == "delicious", "palatable_delicious",
                               ifelse(base == "liked" | base == "loved", "liked_loved",
                                      ifelse(base == "good" | base == "excellent", 
                                             "good_excellent", "memorable_unforgettable"))))) %>%
  group_by(scale, alt) %>%
  summarise(n = n()) %>%
  filter(n >= 10)
```

```{r}
sort(table(d1$all))
sort(table(d1$some))
length(sort(table(d1$all)))
length(sort(table(d1$some)))



mem_un <- sort(table(c(as.character(d1$unforgettable), 
             as.character(d1$memorable))))
mem_un[mem_un > 4]

some_all <- sort(table(c(as.character(d1$some), 
             as.character(d1$all))))
some_all[some_all > 4]

ex_good <- sort(table(c(as.character(d1$excellent), 
             as.character(d1$good))))
ex_good[ex_good > 4]


sort(table(d1$unforgettable))
sort(table(d1$memorable))
length(sort(table(d1$unforgettable)))
length(sort(table(d1$memorable)))

sort(table(d1$excellent))
sort(table(d1$good))
length(sort(table(d1$excellent)))
length(sort(table(d1$good)))

sort(table(d1$loved))
sort(table(d1$liked))
length(sort(table(d1$loved)))
length(sort(table(d1$liked)))

sort(table(d1$delicious))
sort(table(d1$palatable))
length(sort(table(d1$delicious)))
length(sort(table(d1$palatable)))


```


