---
title: "data_cleaning"
author: "BPeloquin"
date: "November 1, 2015"
output: html_document
---


Data cleaning code for Literal listener and Pragmatic listener experiments
```{r}
rm(list = ls())
setwd("~/Desktop/Projects/scalar_implicature/")
library(dplyr)
library(rjson)
```

Literal listener studies
```{r}
data_path = "production-results/"
current_exp = "e6"

# getTurkData
# -----------
# @file_path:   file path to results dir (i.e. "production-results/")
# @ exp_num:    data for specific experiment we're looking at (i.e. "e6")
readTurkData = function(file_path, exp_num) {
  complete_path = paste(file_path, exp_num, "/", sep="")
  files = dir(complete_path, pattern = "*.json")
  d.raw = data.frame()

  for (f in files) {
    jf = paste(complete_path,f,sep="")
    jd = fromJSON(paste(readLines(jf), collapse=""))
    id = data.frame(
      workerid = jd$WorkerId, 
      scale = jd$answer$scale,
      degree = jd$answer$degree,
      stars = as.numeric(jd$answer$judgment),
      language = jd$answer$language)
    d.raw = bind_rows(d.raw, id)
  }
  return(d.raw)
}
d.raw = readTurkData(data_path, current_exp)
head(d.raw)
```

