---
title: "Model Comparisons"
author: "BPeloquin"
output:
  html_document:
    highlight: pygments
    theme: flatly
    toc: yes
    toc_depth: 2
---

Set-up
------

```{r}
rm(list=ls())

library(ggplot2)
library(knitr)
library(rjson)
library(dplyr)
library(tidyr)
#setwd("~/Desktop/Projects/scalar_implicature/")
#source("analysis/useful_dplyr.R")
```

# RSA functionality
```{r}
# speaker informativity
# ---------------------
speaker.lhd = function(d, alpha, cost = 0) {
  exp(alpha*(log(d) - cost))
}
# speaker likelihood
# ------------------
speaker.prob = function(rating, degree, m, alpha) {
  numerator = speaker.lhd(m[rating, degree], alpha)
  norm = 0
  for (i in 1:ncol(m)) {
    norm = norm + speaker.lhd(m[rating, i], alpha)
  }
  return(numerator / norm)
}
# non-normalized posterior
# -----------------------
nn.post = function(rating, degree, m, alpha, useprior) {
  prior = priors[rating, "prior.p"]
  speaker.prob(rating, degree, m, alpha) * prior
}
# normalized posterior
# --------------------
norm.post = function(rating, degree, m, alpha, useprior) {
  nn = nn.post(rating, degree, m, alpha, useprior)
  norm = 0
  for (i in 1:5) {
    # summation over all scale mates
    norm = norm + nn.post(i, degree, m, alpha, useprior)
  }
  return(nn / norm)
}  
```

# Run model functionality
```{r}
# run.partial()
# ------------
# Run RSA with model1 (entailment) and model2 (entailment + generic)
run.partial <- function(d, alpha = 1, useprior = F, usenone = F) {
  mat <- d %>%
    select(stars, degree, speaker.p) %>%
    spread(degree, speaker.p) %>%
    mutate(hi = hi / sum(hi), 
           low = low / sum(low)) %>%
    select(hi, low)
  
  if (usenone) {
    mat$none <- c(1, 0, 0, 0, 0)
  } 
  
  d$pred <- round(as.numeric(mapply(norm.post, d$stars, d$degree, 
                                    MoreArgs = list(m = mat, 
                                                    alpha = alpha, 
                                                    useprior = useprior))), 
                  digits=4)
  
  return(d)
} 

# run.full()
# ------------
# Run RSA with model3 (full) with alternatives
run.full <- function(d, alpha = 1, useprior = F, usenone = F) {
  mat <- d %>%
    select(stars, degree, speaker.p) %>%
    spread(degree, speaker.p) %>%
    mutate(hi1 = hi1 / sum(hi1),
           hi2 = hi2 / sum(hi2),
           low1 = low1 / sum(low1),
           low2 = low2 / sum(low2)) %>%
    select(hi1, hi2, low1, low2)
  
  if (usenone) {
    mat$none <- c(1, 0, 0, 0, 0)
  } 
  
  d$pred <- round(as.numeric(mapply(norm.post, d$stars, d$degree, 
                                    MoreArgs = list(m = mat, 
                                                    alpha = alpha, 
                                                    useprior = useprior))), 
                  digits=4)
  
  return(d)
} 

```

## Tune hyperparams
```{r}
# tune.alhpa()
# ------------
# d        --> data
# alphas   --> range of alphas to test
# type     --> full or partial model
# useprior --> use uniform prior
# usenone  --> use gener None
tune.alpha = function(d, alphas = seq(from=1, to=10), type="partial", useprior = T, usenone=F) {
  # Tune best alphas
  fit = sapply(alphas, FUN=function(n) {
    if (type == "partial") {
      md <- d %>%
        do(run.partial(., alpha = n, useprior = useprior, usenone = usenone))
    } else {
      md <- d %>%
        do(run.full(., alpha = n, useprior = F, usenone = F))
    }
    # MSE
    return(mean((md$pred - md$listener.p)^2))
  })  
  # get lowest MSE
  best.alpha = which(fit == min(fit))
  return(best.alpha)
}
```

# Model Comparisons

## Data for Entailment models
```{r}
speaker = read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e8.csv")
listener = read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L1_e6.csv")
# Uniform priors
priors = data.frame(stars = seq(1, 5), prior.p = rep(0.2, 5))
# Combine speaker / listener
data.partial = left_join(speaker, listener) %>%
  left_join(priors) %>%
  rowwise %>%
  select(scale, degree, stars, speaker.p, listener.p, prior.p) %>%
  mutate(listener.p = ifelse(is.na(listener.p), 0, listener.p)) %>%
  group_by(scale)
```

## Data for full model
```{r}
speaker = read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e10.csv")
listener = read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L1_e11.csv")
data.full = left_join(speaker, listener) %>%
  left_join(priors) %>%
  rowwise %>%
  select(scale, degree, stars, speaker.p, listener.p, prior.p) %>%
  mutate(listener.p = ifelse(is.na(listener.p), 0, listener.p)) %>%
  group_by(scale)
```

## Match items between studies (full and partial)
```{r}
matched.items = which((data.full[, "scale"] != "some_all" &
        (data.full[, "degree"] == "hi2" | data.full[, "degree"] == "hi1")) |
       (data.full[, "scale"] == "some_all" &
          (data.full[, "degree"] == "hi1" | data.full[, "degree"] == "low1")))
```


## Run comparisons
```{r}
# Save performance output
performance.output = data.frame(model=rep(NA, 6), r2=rep(NA, 6))

# Model 1 - Entailment, no alpha tuning
# -------------------------------------
m1.noFit = data.partial %>%
  do(run.partial(., alpha = 1, useprior = T, usenone = F))
performance.output[1, ] = c("M1_noFit", round(cor(m1.noFit$listener.p, m1.noFit$pred)^2, 5))

# Model 1 - Entailment, alpha tuning
# ----------------------------------
best.alpha = tune.alpha(data.partial)
m1.fit = data.partial %>%
  do(run.partial(., alpha = best.alpha))
performance.output[2, ] = c("M1_fit", round(cor(m1.fit$listener.p, m1.fit$pred)^2, 5))

# Model 2 - Entailment, generic "None", no alpha tuning
# -----------------------------------------------------
m2.noFit = data.partial %>%
  do(run.partial(., alpha = 1, usenone = T))
performance.output[3, ] = c("M2_noFit", round(cor(m2.noFit$listener.p, m2.noFit$pred)^2, 5))

# Model 2 - Entailment, generic "None", alpha tuning
# --------------------------------------------------
best.alpha = tune.alpha(data.partial, usenone = T)
m2.fit = data.partial %>%
  do(run.partial(., alpha = best.alpha, usenone = T))
performance.output[4, ] = c("M2_fit", round(cor(m2.fit$listener.p, m2.fit$pred)^2, 5))

# Model 3 - Full, no alpha tuning
# -------------------------------
m3.noFit = data.full %>%
  do(run.full(., alpha = 1))
m3.noFit.matched = m3.noFit[matched.items, ]
performance.output[5, ] = c("M3_noFit", round(cor(m3.noFit.matched$listener.p, m3.noFit.matched$pred)^2, 5))

# Model 3 - Full, alpha tuning
# ----------------------------
best.alpha = tune.alpha(data.full, type = "full")
m3.fit = data.full %>%
  do(run.full(., alpha = best.alpha))
m3.fit.matched = m3.fit[matched.items, ]
performance.output[6, ] = c("M3_fit", round(cor(m3.fit.matched$listener.p, m3.fit.matched$pred)^2, 5))
```

Visualize
---------
```{r}
performance.output
performance.output$model = factor(performance.output$model, levels=c(
  "M1_noFit", "M1_fit", "M2_noFit", "M2_fit", "M3_noFit", "M3_fit"
))
performance.output$r2 = as.numeric(performance.output$r2)
qplot(data=performance.output, x=model, y=performance.output$r2,
      geom="bar", stat="identity",
      main = "Model performance", ylab="r^2", xlab="model") +
  geom_text(aes(label = round(r2, 3), y = r2 + 0.02), size = 3) +
  scale_y_continuous(limits=c(0, 1))


m1.noFit.G = qplot(stars, listener.p, col=degree, 
      data=m1.noFit,
      main="M1, no fit",
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)
m1.noFit.G

m1.fit.G = qplot(stars, listener.p, col=degree, 
      data=m1.fit,
      main="M1, no fit",
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)
m1.fit.G

m2.noFit.G = qplot(stars, listener.p, col=degree, 
      data=m2.noFit,
      main="M2, no fit",
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)
m2.noFit.G

m2.fit.G = qplot(stars, listener.p, col=degree, 
      data=m2.fit,
      main="M2, no fit",
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)
m2.fit.G

m3.matched.noFit.G = qplot(stars, listener.p, col=degree, 
      data=m3.noFit.matched,
      main="M3, no fit",
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)
m3.matched.noFit.G

m3.matched.fit.G = qplot(stars, listener.p, col=degree, 
      data=m3.fit.matched,
      main="M3, no fit",
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)
m3.matched.fit.G
```

