---
title: "Scalar_M1"
author: "BPeloquin"
date: "April 23, 2015"
output: html_document
---

Preliminaries.

```{r}
rm(list=ls())
source("analysis/useful_dplyr.R")
library(rjson)
```

## Notes
* <none, some, all> condition: the model correctly produces implicature.
* However "all"" condition is predicted to be compabitible with a 4 rating.
* This appears to be driven by several factors
  * 1) High priors over 4
  * 2) Fairly high compabitibiliy with All and four stars from e5

## Basic form of the model

$$p_{L_p} (r \mid u) \propto \frac{p_S(u | r) p_{L_0}(r)}{\sum_{u' \in alts}{p_S(u' \mid r) p_{L_0}(r)}}$$

Read Data 
---------

```{r}
priors = read.csv("models/prior.csv")
# Possible transformations
#priors$prior.p = sqrt(priors$prior.p)/(sum(sqrt(priors$prior.p)))
priors$prior.p = (1/(-log(priors$prior.p))) / sum((1/(-log(priors$prior.p))))

speaker = read.csv("models/speaker.csv")
speaker.alt = read.csv("models/e5a.csv")
listener = read.csv("models/listener.csv")
```

## MODEL IMPLEMENTATION

Key:
* u = utterance [string]
* alts = alternative utterances
* r = rating index [1-5]
* d.info = informativity judgements

```{r}
#cost function in length of chars
# u.cost = function(u) {
#   return(nchar(u))
# }

#speaker likelihood helper 
speaker.lhd = function(d, alpha, cost = 0) {
  exp(alpha*(log(d) - cost)) #Rethink alpha and costs?
}

#speaker likelihood normalized
speaker.prob = function(rating, degree, m, alpha) {
  num = speaker.lhd(m[rating, degree], alpha)
  norm = 0
  for (i in 1:ncol(m)) {
    norm = norm + speaker.lhd(m[rating, i], alpha)
  }
  return(num / norm)
}

#non-normalized posterior
nn.post = function(rating, degree, m, alpha, useprior) {
  
  if (useprior) {
    prior <- priors[rating, "prior.p"]
  } else { #unif prior
    prior = .2 
  }
  
  speaker.prob(rating, degree, m, alpha) * prior
}

#normalized posterior
norm.post = function(rating, degree, m, alpha, useprior) {
  nn = nn.post(rating, degree, m, alpha, useprior)
  norm = 0
  for (i in 1:5) {
    norm = norm + nn.post(i, degree, m, alpha, useprior)
  }
  return(nn / norm)
}  
```

model wrapper functions:

```{r}
run.rsa <- function(d, alpha = 1, useprior = TRUE, usenone = FALSE) {

  mat <- d %>%
    select(stars, degree, speaker.p) %>%
    spread(degree, speaker.p) %>%
    mutate(hi = hi / sum(hi), 
           low = low / sum(low)) %>%
    select(hi, low)
  
  if (usenone) {
    mat$none <- c(.8, .2, 0, 0, 0)
    mat$bad <- c(.25, .5, .25, 0, 0)
  } 
  
  d$pred <- round(as.numeric(mapply(norm.post, d$stars, d$degree, 
                                    MoreArgs = list(m = mat, 
                                                    alpha = alpha, 
                                                    useprior = useprior))), 
                  digits=4)
  
  return(d)
} 
```


RUN MODEL
--------

Run model on actual data

```{r}
data <- left_join(speaker, listener) %>%
  left_join(priors) %>%
  rowwise %>%
  select(scale, degree, stars, speaker.p, listener.p, prior.p) %>%
  mutate(listener.p = ifelse(is.na(listener.p), 0, listener.p)) %>%
  group_by(scale)
```

## RUN MODEL 

```{r}
# Which alpha has tightest correlation with human judgements
alphas = seq(from=1, to=20)
fit = sapply(alphas, FUN=function(n) {
  md <- data %>%
    do(run.rsa(., alpha = n, useprior = FALSE, usenone = TRUE))

  mean((md$pred - md$listener.p)^2)
})
qplot(alphas, fit, main="MSE for alpha values", ylab="MSE")
best.alpha = which(fit == min(fit))
best.alpha

# RUN MODEL
md <- data %>%
  do(run.rsa(., alpha = best.alpha, useprior = FALSE, usenone = TRUE))
```

## DATA / PLOTS ------------>

```{r}
# Facets all scales, Model vs Human judgements
qplot(stars, listener.p, col=degree, 
      data = md, main="Model vs Human judgments") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 2)

ggplot(md, aes(x=listener.p, y=pred)) +
    geom_point(aes(colour = stars)) +
    geom_smooth(method=lm) + ggtitle("Model pred vs Human judgment")
cor(md$pred, md$listener.p)
```

Priors
```{r}
qplot(c(1:5), priors$prior.p,
      geom="bar", stat = "identity",
      binwidth = 1, main="Priors over ratings")
```
