---
title: "alternativeRSA"
author: "Ben Peloquin"
date: "January 13, 2016"
output: html_document
---

```{r}
rm(list = ls())
library(ggplot2)
library(knitr)
library(rjson)
library(dplyr)
library(tidyr)
library(gridExtra)
```


Old RSA formulation
```{r}
# speaker informativity
# ---------------------
speaker.inf = function(d, alpha, cost = 0) {
  exp(alpha*(log(d) - cost))
}
# speaker likelihood
# ------------------
speaker.lhd = function(rating, degree, m, alpha) {
  numerator = speaker.inf(m[rating, degree], alpha)
  normalize = sum(sapply(m[rating, ], function(i) {speaker.inf(i, alpha)}))
  return(numerator / normalize)
}
# non-normalized posterior
# -----------------------
nn.post = function(rating, degree, m, alpha, useprior) {
  prior = priors[rating, "prior.p"]
  return(speaker.lhd(rating, degree, m, alpha) * prior)
}
# normalized posterior
# --------------------
norm.post = function(rating, degree, m, alpha, useprior) {
  nn = nn.post(rating, degree, m, alpha, useprior)
  normalize = sum(unlist(sapply(seq(1, 5),
                                function(i){nn.post(i, degree, m, alpha, useprior)})))
  return(nn / normalize)
}
```

New Prior incorporation
```{r}
speaker.inf3 = function(d, alpha, cost = 0) {
  if (d == 0) return(0)
  exp(-1 * alpha * (-log(d) - cost))
  # exp(alpha * (log(d) - cost))
}
# speaker likelihood
# ------------------
speaker.lhd3 = function(currRating, currDegree, m, alpha, costs, allDegrees) {
  currCost <- subset(costs, degree == currDegree)$cost
  numerator = speaker.inf3(m[[currDegree]][currRating], alpha, currCost)
  # normalize over other words
  normalize <- sum(unlist(sapply(seq(allDegrees), FUN = 
                            function(i) {
                              speaker.inf3(m[[allDegrees[i]]][currRating], alpha,
                                          subset(costs, degree == allDegrees[i])$cost)}
                          )))
  if (normalize == 0) return(0)
  return(numerator / normalize)
  # return(numerator)
}

# non-normalized posterior
# -----------------------
nn.post3 = function(currRating, currDegree, m, alpha, costs, priors, allDegrees) {
  # prior <- priors[rating, "prior.p"]
  # prior <- costs[degree]
  currPrior <- subset(priors, stars == currRating)$prior.p
  return(speaker.lhd3(currRating, currDegree, m, alpha, costs, allDegrees) * currPrior)
}
# normalized posterior
# --------------------
norm.post3 = function(currRating, currDegree, m, alpha, costs, priors, allDegrees) {
  nn <- nn.post3(currRating, currDegree, m, alpha, costs, priors, allDegrees)
  normalize <- sum(unlist(sapply(seq(1, 5),
                                function(i) {
                                  nn.post3(i, currDegree, m, alpha, costs, priors, allDegrees)}
                                )))
  return(nn / normalize)
}

normedVec <- function(vec) {
  vec / sum(vec)
}
```

Run RSA
```{r}
computePosteriors <- c(norm.post, norm.post3)
# runFull() 
# ---------
# data       => contains scale | degree | stars | speaker.p | prior.p | cost
# calcFN     => without cost = 1, with cost = 2
# alpha      => set alpha level
runFull <- function(data, calcFn = 2, alpha = 1, numAlts = 5) {
  results <-
    data.frame(scale = c(),
               stars = c(),
               degree = c(),
               preds = c())
  
  scales <- unique(data$scale)
  for (s in scales) {
      if (numAlts == 5) {
        mat <- subset(data, scale  == s) %>%
          select(stars, degree, speaker.p) %>%
          spread(degree, speaker.p) %>%
          mutate(hi1 = hi1 / sum(hi1),
                 hi2 = hi2 / sum(hi2),
                 mid = mid / sum(mid),
                 low1 = low1 / sum(low1),
                 low2 = low2 / sum(low2)) %>%
          select(hi1, hi2, mid, low1, low2)
      } else if (numAlts == 4) {
        mat <- subset(data, scale  == s) %>%
          select(stars, degree, speaker.p) %>%
          spread(degree, speaker.p) %>%
          mutate(hi1 = hi1 / sum(hi1),
                 hi2 = hi2 / sum(hi2),
                 low1 = low1 / sum(low1),
                 low2 = low2 / sum(low2)) %>%
          select(hi1, hi2, low1, low2)
      } else if (numAlts == 3) {
        mat <- subset(data, scale  == s) %>%
          select(stars, degree, speaker.p) %>%
          spread(degree, speaker.p) %>%
          mutate(hi = hi / sum(hi),
                 low = low / sum(low),
                 none = none / sum(none)) %>%
          select(hi, low, none)
      } else if (numAlts == 2) {
        mat <- subset(data, scale  == s) %>%
          select(stars, degree, speaker.p) %>%
          spread(degree, speaker.p) %>%
          mutate(hi = hi / sum(hi),
                 low = low / sum(low)) %>%
          select(hi, low)
      }
    stars <- subset(data, scale == s)$stars
    degrees <- as.character(subset(data, scale == s)$degree)
    currCosts <- unique(subset(data, scale == s) %>% select(degree, cost))
    priors <- data %>% select(c(stars, prior.p)) %>% head(., n=5)
    
    results <- rbind(results,
                     data.frame(scale = s,
                                preds =
                                  as.numeric(mapply(computePosteriors[[calcFn]],
                                                    stars,
                                                    degrees,
                                                    MoreArgs =
                                                      list(m = mat,
                                                           alpha = alpha,
                                                           costs = currCosts,
                                                           priors = priors,
                                                           allDegrees = unique(degrees)))),
                                stars = stars,
                                degree = degrees,
                                stringsAsFactors = FALSE))
  }
  left_join(data, results)
}
```


Data set-up
```{r}
# All scales studied
# ------------------
scales <- c("good_excellent",
            "liked_loved",
            "palatable_delicious",
            "memorable_unforgettable",
            "some_all")
# Priors
# ------
unifPriors = data.frame(stars = seq(1, 5), prior.p = rep(0.2, 5))
empPriors = read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/emp_priors.csv")
yelpPriors <- data.frame(stars=1:5,
                         prior.p =
                           c(0.090190981, 0.105689431, 0.162783722, 0.304569543, 0.336766323))
# Cost / rewards
# --------------
# for five alts
emptyCosts5 <- data.frame(scale = c(rep("good_excellent", 5),
                                    rep("liked_loved", 5),
                                    rep("memorable_unforgettable", 5),
                                    rep("palatable_delicious", 5),
                                    rep("some_all", 5)),
                          degree = rep(c("hi1", "hi2", "mid", "low1", "low2"), 5),
                          newCount = rep(0.0, 25),
                          stringsAsFactors = FALSE)
# for four alts
emptyCosts4 <- data.frame(scale = c(rep("good_excellent", 4),
                                    rep("liked_loved", 4),
                                    rep("memorable_unforgettable", 4),
                                    rep("palatable_delicious", 4),
                                    rep("some_all", 4)),
                          degree = rep(c("hi1", "hi2", "low1", "low2"), 5),
                          newCount = rep(0.0, 20),
                          stringsAsFactors = FALSE)
# Used with generic none run
emptyCosts3 <- data.frame(scale = c(rep("good_excellent", 3),
                                    rep("liked_loved", 3),
                                    rep("memorable_unforgettable", 3),
                                    rep("palatable_delicious", 3),
                                    rep("some_all", 3)),
                          degree = rep(c("hi", "low", "none"), 5),
                          newCount = rep(0.0, 15),
                          stringsAsFactors = FALSE)
# for two-alts
emptyCosts2 <- data.frame(scale = c(rep("good_excellent", 2),
                                    rep("liked_loved", 2),
                                    rep("memorable_unforgettable", 2),
                                    rep("palatable_delicious", 2),
                                    rep("some_all", 2)),
                          degree = rep(c("hi", "low"), 5),
                          newCount = rep(0.0, 10),
                          stringsAsFactors = FALSE)

# degree = c("low2", "low1", "mid", "hi2", "hi1"),
#                             newCount = rep(0.0, 5), stringsAsFactors = FALSE)
# emptyCosts4 <- data.frame(degree = c("low2", "low1","hi2", "hi1"),
#                             newCount = rep(0.0, 4), stringsAsFactors = FALSE)
# emptyCosts2 <- data.frame(degree = c("low", "hi"),
#                             newCount = rep(0.0, 2), stringsAsFactors = FALSE)
salienceCosts5 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/saliences5.csv")
salienceCosts4 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/saliences4.csv")
salienceCosts2 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/saliences2.csv")
# normNegSalienceCosts <- function(saliences) {
#   for (s in scales) {
#     saliences[saliences$scale == s, ]$cost <-
#       -1 * normedVec(saliences[saliences$scale == s, ]$cost)
#   }
#   saliences
# }
# salience <- c(0.22, 0.08, 0.05, 1, 1)
# saliencePriors <- data.frame(stars=1:5, prior.p = (salience / sum(salience)))
# salienceCosts <- data.frame(degree = c("low2", "low1", "mid", "hi2", "hi1"),
#                             cost = -1 * (salience / sum(salience)), stringsAsFactors = FALSE)

# Speaker
# -------
speakerL12 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e12.csv")
speakerL10 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e10.csv")
speakerGenericNone <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e8_genericNone.csv")
speakerL08 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e8.csv")
speakerL08 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L0_e8Compliance.csv")
# Listener
# --------
listener <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L1_e6.csv")
listener2 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L1_e11.csv", stringsAsFactors = FALSE)


############# NEW SALIENCES 1/20/16 #########
salienceCosts5 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/saliences5.csv")
NUM_ALTERNATIVES_E9 <- 180
normNegSalienceCosts <- function(saliences) {
  # Add cost column
  saliences$cost <- c(rep(0, nrow(saliences)))
  
  # Check if we've passed emptyCost
  if (all(saliences$newCount == 0)) return(saliences[, c("scale", "degree", "cost")])
  
  for (s in scales) {
    saliences[saliences$scale == s, ]$cost <-
      saliences[saliences$scale == s, ]$newCount / NUM_ALTERNATIVES_E9
    
    saliences[saliences$scale == s, ]$cost <- 1 / log(saliences[saliences$scale == s, ]$cost)
  }
  saliences[, c("scale", "degree", "cost")]
}
############# NEW SALIENCES 1/20/16 #########

# costs <- normNegSalienceCosts(salienceCosts5)
# priors <- unifPriors
# data <- left_join(speakerL12, costs) %>%
#   left_join(., priors) %>%
#   rowwise %>%
#   select(scale, degree, stars, speaker.p, prior.p, cost) %>%
#   group_by(scale)

# run fns()
# ---------
# checkSaliences()
# tuneAlphas(modelData = data, humanDf = listener, numAlts = 2)
```

Data exploration Fns()
```{r}
# matchModelHumandData()
# -----------------------
matchModelHumanData <- function(predDf, listenerDf, study = "e12") {
  combinedDf <- data.frame(scale = c(),
                           degree = c(),
                           speaker.p = c(),
                           prior.p = c(),
                           cost = c(),
                           preds = c())
  
  for (s in unique(predDf$scale)) {
    if (study == "e12") {
      if (s == "some_all") {
        tempDf <- subset(predDf, scale == s & (degree == "hi1" | degree == "mid")) %>%
          mutate(degree = ifelse(degree == "hi1", "hi", "low"))
        } else {
          tempDf <- subset(predDf, scale == s & (degree == "hi1" | degree == "hi2")) %>%
            mutate(degree = ifelse(degree == "hi1", "hi", "low"))
        }
    } else if (study == "e10") {
        if (s == "some_all") {
          tempDf <- subset(predDf, scale == s & (degree == "hi1" | degree == "low1")) %>%
            mutate(degree = ifelse(degree == "hi1", "hi", "low"))
        } else {
          tempDf <- subset(predDf, scale == s & (degree == "hi1" | degree == "hi2")) %>%
            mutate(degree = ifelse(degree == "hi1", "hi", "low"))
        }
    } else if (study == "genericNone") {
      tempDf <- subset(predDf, scale == s & degree != "none")
    } else { ## study e6
      tempDf <- subset(predDf, scale == s)
    }
    
    combinedDf <- rbind(combinedDf, tempDf)
  }

  results <- merge(x = combinedDf,
                   y = listenerDf,
                   by = c("degree", "stars", "scale"),
                   all.x = TRUE) %>%
    mutate(listener.p = ifelse(is.na(listener.p), 0, listener.p))
  
  results
}
# mergedData <- matchModelHumanData(data, listener, study = "e6")

# Alpha Tuning - maximixize correlation
# -------------------------------------
tuneAlphas <- function(modelData, humanDf, alphas = seq(1, 12), numAlts = 5, study = "e12"){
  sapply(alphas, function(i) {
    predDf <- runFull(modelData, calcFn = 2, alpha = i, numAlts = numAlts)
    # Watch for generic none run
    if (study == "genericNone") {
      mergedData <- matchModelHumanData(subset(predDf, degree != "none"), listener, study = study)
    } else {
      mergedData <- matchModelHumanData(predDf, listener, study = study)
    }
    cor(mergedData$preds, mergedData$listener.p)
  })
}
# tuneAlphas(modelData = data, humanDf = listener, numAlts = 4)

checkSaliences <- function(d, study = "e12", alpha = 1, numAlts = 5) {
  predDf <- runFull(d, calcFn = 2, alpha = alpha, numAlts = numAlts)
  mergedData <- matchModelHumanData(predDf, listener, study = study)
  cor(mergedData$preds, mergedData$listener.p)
}
# checkSaliences(data, study = "e6", alpha = 1, numAlts = 2)
```


Visualize
```{r}
# mergedData <- matchModelHumanData(runFull(data, calcFn = 2, alpha = 7, numAlts = 5), listener)
# plotData <- mergedData

# predPlot()
# ---------
# plot preds over stars with human data
predPlot <- function(d) {
  qplot(stars, listener.p, col=degree,
      data=d,
      main=paste("title")) +
  ylim(0, 1) +
  facet_wrap(~scale) + 
  geom_line(aes(y = preds), lty = 4)
}
# correlationScatterPlot()
# -----------------------
# plot correleation with low / hi
correlationScatterPlot <- function(d) {
  ggplot(d, aes(x = listener.p, y = preds, col=stars)) +
  geom_point() + 
  stat_smooth(method="lm")
}
```

Run full model analysis
```{r}
# completeModelRun()
# ------------------
completeModelRun <- function(speaker, listener, priors, costs, numAlts) {
  results <- list() ## Will return this
  newCosts <- normNegSalienceCosts(costs)
  
  data <- left_join(speaker, newCosts) %>%
    left_join(., priors) %>%
    rowwise %>%
    select(scale, degree, stars, speaker.p, prior.p, cost) %>%
    group_by(scale)

  studyNum <- ifelse(numAlts == 5, "e12",
                     ifelse(numAlts == 4, "e10",
                            ifelse(numAlts == 3, "genericNone", "e6")))
  # Tune alpha
  bestAlpha <- which.max(tuneAlphas(data, listener, numAlts = numAlts, study = studyNum))
  # Run model
  modelData <- runFull(data, calcFn = 2, alpha = bestAlpha, numAlts = numAlts)
  # Final data set for plotting / model fit
  
  combinedDf <- matchModelHumanData(modelData, listener, study = studyNum)
  fit <- cor(combinedDf$preds, combinedDf$listener.p)

  results[[1]] <- combinedDf
  results[[2]] <- modelData
  results[[3]] <- bestAlpha
  results[[4]] <- fit
  results[[5]] <- predPlot(combinedDf)
  results[[6]] <- correlationScatterPlot(combinedDf)
  results
}
```

Run complete analyses and output to csv
```{r}
# Run analyses
fiveAlts <- completeModelRun(speakerL12, listener, unifPriors, emptyCosts5, numAlts = 5)
fiveAlts[[4]]
fourAlts <- completeModelRun(speakerL10, listener, unifPriors, emptyCosts4, numAlts = 4)
fourAlts[[4]]
twoAltsGenericNone <- completeModelRun(speakerGenericNone, listener, unifPriors, emptyCosts3, numAlts = 3)
twoAltsGenericNone[[4]]
twoAlts <- completeModelRun(speakerL08, listener, unifPriors, emptyCosts2, numAlts = 2)
twoAlts[[4]]


listener2 <- read.csv("~/Desktop/Projects/scalar_implicature/models/model_data/L1_e11.csv", stringsAsFactors = FALSE)
fiveAltsData <- fiveAlts[[1]]
fiveAltsData$numAlts = 5
fourAltsData <- fourAlts[[1]]
fourAltsData$numAlts = 4
twoAltsGenericNoneData <- twoAltsGenericNone[[1]]
twoAltsGenericNoneData$numAlts = 3
twoAltsData <- twoAlts[[1]]
twoAltsData$numAlts = 2

# Aggregate data to write to .csv

# combine with e11 prag listener nums
aggregateData <- rbind(fiveAltsData, fourAltsData, twoAltsGenericNoneData, twoAltsData)
listener2 <- listener2[(listener2$scale == "some_all" & (listener2$degree == "low1" | listener2$degree == "hi1")) |
                         (listener2$scale != "some_all" & (listener2$degree == "hi1" | listener2$degree == "hi2")), ]
listener2$degree <- as.character(ifelse(listener2$degree == "hi1", "hi", "low"))
names(listener2) <- c("degree", "scale", "stars", "listener.p2", "total")
aggregateData <- left_join(aggregateData, listener2[, -5], by=c("degree", "stars", "scale")) %>%
  mutate(listener.p2 = ifelse(is.na(listener.p2), 0, listener.p2))


# record correlations for both studies
modelRunData <- aggregateData
fiveAltsE6cor <- cor(subset(modelRunData, numAlts == 5)$preds, subset(modelRunData, numAlts == 5)$listener.p)
fiveAltsE11cor <-cor(subset(modelRunData, numAlts == 5)$preds, subset(modelRunData, numAlts == 5)$listener.p2)
fourAltsE6cor <- cor(subset(modelRunData, numAlts == 4)$preds, subset(modelRunData, numAlts == 4)$listener.p)
fourAltsE11cor <- cor(subset(modelRunData, numAlts == 4)$preds, subset(modelRunData, numAlts == 4)$listener.p2)
twoAltsGenericNoneE6cor <-
  cor(subset(modelRunData, numAlts == 3)$preds, subset(modelRunData, numAlts == 3)$listener.p)
twoAltsGenericNoneE11cor <-
  cor(subset(modelRunData, numAlts == 3)$preds, subset(modelRunData, numAlts == 3)$listener.p2)
twoAltsE6cor <- cor(subset(modelRunData, numAlts == 2)$preds, subset(modelRunData, numAlts == 2)$listener.p)
twoAltsE11cor <- cor(subset(modelRunData, numAlts == 2)$preds, subset(modelRunData, numAlts == 2)$listener.p2)


modelRunData$corE6 <- ifelse(modelRunData$numAlts == 5, fiveAltsE6cor,
                             ifelse(modelRunData$numAlts == 4, fourAltsE6cor,
                                    ifelse(modelRunData$numAlts == 3, twoAltsGenericNoneE6cor, twoAltsE6cor)))
modelRunData$corE11 <- ifelse(modelRunData$numAlts == 5, fiveAltsE11cor,
                             ifelse(modelRunData$numAlts == 4, fourAltsE11cor,
                                    ifelse(modelRunData$numAlts == 3, twoAltsGenericNoneE11cor, twoAltsE11cor)))
modelRunData$alphas <- ifelse(modelRunData$numAlts == 5, fiveAlts[[3]],
                             ifelse(modelRunData$numAlts == 4, fourAlts[[3]],
                                    ifelse(modelRunData$numAlts == 3, twoAltsGenericNone[[3]], twoAlts[[3]])))

# write.csv(modelRunData, "~/Desktop/Projects/scalar_implicature/models/model_data/allModelRuns.csv")
```
