---
title: "RSA_model2"
author: "BPeloquin"
date: "August 6, 2015"
output: html_document
---

Set-up
------

```{r}
rm(list=ls())

library(ggplot2)
library(knitr)
library(rjson)
library(dplyr)
library(tidyr)

#setwd("~/Desktop/Projects/scalar_implicature/")
#source("analysis/useful_dplyr.R")
```

Data
----
```{r}
speaker = read.csv("~/Desktop/Projects/scalar_implicature/models/e8.csv")
listener = read.csv("~/Desktop/Projects/scalar_implicature/models/listener.csv")
# priors
# ------
unif = data.frame(stars = seq(1, 5), prior.p = rep(0.2, 5))
empirical = read.csv("~/Desktop/Projects/scalar_implicature//models/prior.csv")
yelp = read.csv("~/Desktop/Projects/scalar_implicature//models/yelp1_priors.csv")
priors = unif
# combine speaker / listener
data <- left_join(speaker, listener) %>%
  left_join(priors) %>%
  rowwise %>%
  select(scale, degree, stars, speaker.p, listener.p, prior.p) %>%
  mutate(listener.p = ifelse(is.na(listener.p), 0, listener.p)) %>%
  group_by(scale)
head(data)
```

Model
-----
```{r}
# speaker informativity
# ---------------------
speaker.lhd = function(d, alpha, cost = 0) {
  exp(alpha*(log(d) - cost))
}
# speaker likelihood
# ------------------
speaker.prob = function(rating, degree, m, alpha) {
  numerator = speaker.lhd(m[rating, degree], alpha)
  norm = 0
  for (i in 1:ncol(m)) {
    norm = norm + speaker.lhd(m[rating, i], alpha)
  }
  return(numerator / norm)
}
# non-normalized posterior
# -----------------------
nn.post = function(rating, degree, m, alpha, useprior) {
  prior = priors[rating, "prior.p"]
  speaker.prob(rating, degree, m, alpha) * prior
}
# normalized posterior
# --------------------
norm.post = function(rating, degree, m, alpha, useprior) {
  nn = nn.post(rating, degree, m, alpha, useprior)
  norm = 0
  for (i in 1:5) {
    # summation over all scale mates
    norm = norm + nn.post(i, degree, m, alpha, useprior)
  }
  return(nn / norm)
}  
```

Run Model
----------
```{r}
# Run rsa model
# --------------------
run.rsa <- function(d, alpha = 1, useprior = F, usenone = F) {

  mat <- d %>%
    select(stars, degree, speaker.p) %>%
    spread(degree, speaker.p) %>%
    mutate(hi = hi / sum(hi), 
           low = low / sum(low)) %>%
    select(hi, low)
  
  if (usenone) {
    mat$none <- c(1, 0, 0, 0, 0)
    #mat$meh <- c(0.0, 0.2, 0.6, 0.2, 0)
    #mat$bad <- c(.5, .9, .4, .1, 0)
  } 
  
  d$pred <- round(as.numeric(mapply(norm.post, d$stars, d$degree, 
                                    MoreArgs = list(m = mat, 
                                                    alpha = alpha, 
                                                    useprior = useprior))), 
                  digits=4)
  
  return(d)
} 
```

Run model
---------
```{r}
alpha = 5
md <- data %>%
  do(run.rsa(., alpha = alpha, useprior = T, usenone = F))
```

Visualize
---------
```{r}
qplot(stars, listener.p, col=degree, 
      data=md,
      main=paste("Model vs Human judgments\nSemantics measured empirically\nalpha=",
                 alpha),
      ylab="Posterior p(rating | word)") + 
  facet_wrap(~scale) + 
  geom_line(aes(y = pred), lty = 4)

ggplot(md, aes(x=pred, y=listener.p)) +
    geom_point(aes(colour = stars)) +
    geom_smooth(method=lm) +
  ggtitle("Model performance: Baseline") +
  labs(x = "model prediction", y="human judgments")
cor(md$pred, md$listener.p)^2
cor.test(md$pred, md$listener.p)
# scalar level cor
specific.cor = function(scalar) {
  return (cor(md[which(md$scale==scalar), ]$pred,
              md[which(md$scale==scalar), ]$listener.p))
}
qplot(unique(md$scale), y = sapply(unique(md$scale), specific.cor),
    aes(group=1), geom="bar", stat="identity")
```

Tuning
-------
```{r}
# alpha
alphas = seq(from=1, to=10)
fit = sapply(alphas, FUN=function(n) {
  md <- data %>%
    do(run.rsa(., alpha = n, useprior = F, usenone = F))
  
  return(mean((md$pred - md$listener.p)^2))
  #return(cor(md$pred, md$listener.p))
})
qplot(alphas, fit, main="Cor for alpha values", ylab="MSE")
best.alpha = which(fit == min(fit))
best.alpha
```


For Presentation to Symsys290 10.26.15
```{r}
qplot(stars, listener.p, col=degree, 
      data=md[md$scale=="some_all",],
      main=paste("Model vs Human judgments\nalpha=",
                 alpha),
      ylab="Posterior p(m | u)") +
  geom_line(aes(y = pred), lty = 4)
```

